[package]
name = "weekly_planner"
version = "0.1.0"
edition = "2021"
default-run = "main"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

[[bin]]
name = "generate_plan"
path = "bin/generate_plan.rs"

[[bin]]
name = "main"
path = "src/main.rs"